import Signup from "@/components/signup/Signup";
import Head from "next/head";
import React from "react";

const signup = () => {
  return (
    <>
      <Head>
        <title>Create account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center">
        <h1 className="text-red-500 md:text-blue-400">Signup page</h1>
      </main>
    </>
  );
};

export default signup;
